# Generated by Django 5.2 on 2026-04-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibiblio', '0002_imatgellibre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imatgellibre',
            name='desc',
        ),
        migrations.AlterField(
            model_name='imatgellibre',
            name='imatge',
            field=models.ImageField(blank=True, null=True, upload_to='llibres/'),
        ),
    ]
